server:
 servlet:
  context-path: /spring-cloud-server
 port: 19527

logging:
 level:
  com:
   postgres:
    mapper: debug

spring:
 application:
  name: cloud-server-one
 cloud:
  nacos:
   discovery:
    server-addr: 127.0.0.1:8848
    namespace: neo
  loadbalancer:
   ribbon:
    enabled: false